version: '3.9'
services:
  django:
    build: .
    container_name: django-search
    command: bash -c "python manage.py migrate && python manage.py init_search && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SEARCH_ENGINE=elasticsearch
      - SOLR_URL=http://solr:8983/solr/search_core
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - solr

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  solr:
    image: solr:9.5
    container_name: solr
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - search_core